#!/usr/bin/perl -w

use strict;
use Getopt::Long;
my ($fh1,$fh2);
my ($rnajunc,$input);
#my ($length) = (50);
GetOptions(
            'j|rnaseqJuncscore=s'       => \$rnajunc,
            'i|input=s'                   => \$input,
            'h|help'        => sub{usage()}
        ) || usage();

open $fh1,"< $rnajunc" or die "Cannot open $rnajunc !";
open $fh2,"< $input" or die "Cannot open $input !";
my(%jhash,@junc);
while (<$fh1>)
{
    chomp;
    my($jchr,$jstart,$jend,$jstrand)=(split/\t/)[0,1,2,5];
    $jhash{"$jchr".'|'."$jstart".'|'."$jend".'|'."$jstrand"}=1;
}
while (<$fh2>)
{
    my $last=0;
    chomp;
    my @pacbio=split/\t/;
    next if $pacbio[7]==1;
    my @start=split/,/,$pacbio[8];
    my @end=split/,/,$pacbio[9];
    shift @start;
    pop @end;
    for (my $i=0;$i<@end;$i++)
    {
        my $startnew=$start[$i]+1;
        my $key="$pacbio[1]".'|'."$end[$i]".'|'."$startnew".'|'."$pacbio[2]";
        if (exists $jhash{$key}) {next;}
        else {$last=1;last;}
    }
    if($last==0){print join "\t",@pacbio;print "\n";}
}
sub usage{
print <<HELP;
Usage: perl juncRNAseqConfirm.pl -j junctions.bed -i non_confirm.r1.gp >Confirm.r2.gp
    If spliced.bed12+ isn't specified, input from STDIN
    Scores will be appended to input entry in the order of lScore (from spliced.bed12+), jScore (from junctions.bed ) and rScore (from hg18.refGene.gpe).
Options:
    -j --junc       FILE    The output of gpe2Junction.pl file (generated by RNAseq juncfile.bed => gpe2Junction.pl)
    -i --input      FILE    pacbio reads => non_confirm.r1.gp
    -h --help               Print this help information
HELP
    exit(-1);
}